import React from "react";
import classes from "./Features.module.css";
import img1 from "../assets/Group 287.svg";
import img3 from "../assets/Group 291.svg";
import img2 from "../assets/Group 294.svg";
function Features() {
  return (
    <>
      <div className={classes.container}>
        <div className={classes.features}>
          <div className={classes.feature}>
            <img src={img1} />
            <h3>Search</h3>
            <p>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
          </div>
          <div className={classes.feature}>
            <img src={img2} />
            <h3>Select</h3>
            <p>Choose from thousands of options generated by the slogan maker that fit your needs.</p>
          </div>
          <div className={classes.feature}>
            <div id={classes.circle}>
              <img src={img3} />
            </div>
            <h3>Stand out</h3>
            <p>Congrats on your new slogan. It's time to win the world!</p>
          </div>
        </div>
      </div>
    </>
  );
}

export default Features;
